name: Software Bill of Material

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  LATEST_TAG: ghcr.io/${{ github.repository }}:latest

jobs:
  sbom:
    permissions:
      actions: read
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.LATEST_TAG }}

      ############## Version 1 ##############
      #- uses: anchore/sbom-action@v0
      #  with:
      #    image: ${{ env.LATEST_TAG }}
      #######################################
